# Generated by Django 4.1.1 on 2022-10-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.ManyToManyField(blank=True, related_name='users', to='orders.order'),
        ),
    ]
